package com.github.fishio.achievements;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;

import com.esotericsoftware.yamlbeans.YamlReader;
import com.esotericsoftware.yamlbeans.YamlWriter;
import com.github.fishio.logging.Log;
import com.github.fishio.logging.LogLevel;

/**
 * This class is responsible for the Input and Output of Achievements to and
 * from file, making sure that the achievements are saved and loaded.
 *
 */
public final class AchievementIO {

	/**
	 * Private constructor for this final class.
	 */
	private AchievementIO() {
	}
	
	private static File achievementFile = new File("achievements.yml");
	private static Log logger = Log.getLogger();
	private static HashMap<String, Integer> achievemap = new HashMap<>();
	
	/**
	 * Adds a counter from an Achievement Observer to the achievement HashMap.
	 * 
	 * @param name
	 *            Name of the Achievement that is Observed.
	 * @param value
	 *            Value of the counter in the Achievement Observer.
	 */
	public static void addObserverCounter(String name, int value) {
		achievemap.put(name, value);
	}
	
	/**
	 * Save the high scores to 'highscores.yml'.
	 */
	public static void save() {
		try (FileWriter bw = new FileWriter(achievementFile)) {
			YamlWriter yw = new YamlWriter(bw);			
			yw.write(achievemap);
			yw.close();
		} catch (IOException e) {
			logger.log(LogLevel.ERROR, "Error writing file " + achievementFile.getAbsolutePath());
			logger.log(LogLevel.DEBUG, e);
		} 
	}

	/**
	 * load the achievements from 'achievemap.yml'.
	 */
	@SuppressWarnings("unchecked")
	public static void load() {
		try (FileReader fr = new FileReader(achievementFile)) {
			YamlReader reader = new YamlReader(fr);
			HashMap<String, String> temp = (HashMap<String, String>) reader.read();
			reader.close();
			if (temp == null) {
				return;
			}
			for (String key : temp.keySet()) {
				achievemap.put(key, Integer.valueOf(temp.get(key)));
			}
		} catch (Exception e) {
			logger.log(LogLevel.ERROR, "Error loading file " + achievementFile.getAbsolutePath());
			logger.log(LogLevel.DEBUG, e);
		}
	}

	/**
	 * A method to read out the HashMap that is generated by loading the yml
	 * file.
	 * 
	 * @param key
	 *            The achievement to read out.
	 * @return The value of this achievement's counter.
	 */
	public static int get(String key) {
		Integer val = achievemap.get(key);
		if (val == null) {
			load();
			 val = achievemap.get(key);
		}
		if (val == null) {
			return 0;
		}
		return val.intValue();
	}

	/**
	 * Set the file for the achievements. This method should only be used for
	 * testing.
	 * 
	 * @param newFile
	 *            The new file.
	 */
	protected static void setAchievementFile(File newFile) {
		achievementFile = newFile;
	}

	/**
	 * @return The hashmap containing all the achievements.
	 */
	public static HashMap<String, Integer> getAll() {
		return achievemap;
	}
}
